# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  fmt:
    cmd: go fmt ./...
    silent: true

  go-build:
    cmds:
      - |
        docker run --rm -it -v {{.USER_WORKING_DIR}}:/go/src golang:1.21-bookworm \
        go build \
        -C /go/src \
        -buildvcs=false \
        -o dist/e-ink-dashboard ./...
    silent: true

  docker-build:
    deps:
      - go-build
    cmds:
      - docker build -t e-ink-dashboard:latest .
    silent: true
